repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format
-   repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
    -   id: auto-walrus
-   repo: local
    hooks:
      - id: generate-feature-table
        name: Generate feature table for README
        entry: python utils/feature_table.py
        language: system